In [ ]:
# WAP to print your name three times
print("Harshita\nHarshita\nHarshita")

Harshita
Harshita
Harshita

In [ ]:
# WAP to add three numbers and print the result.
num1 = 3
num2 = 4
num3 = 8
sum = num1+num2+num3
print('Sum is' , sum)

Sum is 15

In [ ]:
#  WAP to concatinate three strings and print the result.
string1 = 'Harshita'
string2 = ' Narula'
string3 = ' Roll Number: 102317003'
print(string1 + string2 + string3)

Harshita Narula Roll Number: 102317003

In [ ]:
# WAP to print the table of 7, 9.
print('Table of 7: ')
for i in range (1,11):
    print(7 , 'x' , i , '=' , 7*i)
print(' ')
print('Table of 9: ')
for i in range (1,11):
    print(9 , 'x' , i , '=' , 9*i)

Table of 7:
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

Table of 9:
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

In [ ]:
#  WAP to print the table of n and n is given by user.
n = int(input('Enter the number: '))
print(' ')
print('Table of ' , n , ' : ')
for i in range (1,11):
    print(n , 'x' , i , '=' , n*i)

Enter the number: 4

Table of  4  :
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

In [ ]:
# WAP to add all the numbers from 1 to n and n is given by user.
n = int(input('Enter the number : '))
sum = 0
for i in range(1,n+1):
    sum = sum + i
print('Sum is : ', sum)

Enter the number : 5
Sum is :  15

In [ ]:
#  WAP to find max amoung three numbers and input from user. [Try max() function]
num1 = int(input('Enter first number: '))
num2 = int(input('Enter second number: '))
num3 = int(input('Enter third number: '))
print('Maximum out of these is ', max(num1,num2,num3))

Enter first number: 4
Enter second number: 5
Enter third number: 1
Maximum out of these is  5

In [ ]:
#  WAP to add all numbers divisible by 7 and 9 from 1 to n and n is given by the user.
n = int(input("Enter the value of n: "))
sum = 0
for i in range(1, n + 1):
    if i % 7 == 0 and i % 9 == 0:
        sum = sum + i
print("Sum of numbers divisible by 7 and 9 from 1 to ", n ," is: ", sum)

Enter the value of n: 63
Sum of numbers divisible by 7 and 9 from 1 to  63  is:  63

In [ ]:
# WAP to add all prime numbers from 1 to n and n is given by the user.
n = int(input("Enter the value of n: "))
sum = 0
for num in range(2, n + 1):
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        sum = sum + num

# Print the result
print("Sum of prime numbers from 1 to ", n, " is: " , sum)

Enter the value of n: 10
Sum of prime numbers from 1 to  10  is:  17

In [ ]:
# WAP using function that add all odd numbers from 1 to n, n is given by the user.
def odd_sum(n):
    sum = 0
    for i in range(1, n + 1, 2):  # Iterate through odd numbers only
        sum = sum + i
    return sum

n = int(input("Enter the value of n: "))
print("Sum of odd numbers from 1 to " , n , " is: " , odd_sum(n))

Enter the value of n: 10
Sum of odd numbers from 1 to  10  is:  25

In [17]:
#  WAP using function that add all prime numbers from 1 to n, n given by the user.
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True

def sum_prime(n):
    sum = 0
    for i in range(2, n + 1):
        if is_prime(i):
            sum = sum + i
    return sum

n = int(input("Enter the value of n: "))
print("Sum of prime numbers from 1 to " , n , " is: " , sum_prime(n))

Enter the value of n: 4
Sum of prime numbers from 1 to  4  is:  5